######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 3 18:56:22 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += boid.hpp landscape.hpp mainwindow.hpp
SOURCES += qboids.cpp boid.cpp landscape.cpp mainwindow.cpp
